config/routes.rb
Rails.application.routes.draw do


  get 'settings/account'

  get 'settings/password'

  get 'settings/notifications'

  get 'settings/profile'

  patch 'settings/update_info' =>"settings#update_info"
  post 'settings/update_image' =>"settings#update_image"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    member do
      get 'username'
    end
  end

  root "pages#home"
  get 'faq', to: 'pages#faq'

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "join", :to => "devise/registrations#new"
    get "logout", :to => "devise/sessions#destroy"
  end


end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  	belongs_to :user

	after_create :fetch_details



	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.username = facebook_data['name']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :email
  #mount_uploader :image, ImageUploader
  has_many :authorizations
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
  :url  => "/assets/avatars/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/avatars/:id/:style/:basename.:extension"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
       user = User.new
       
       user.password = Devise.friendly_token[0,10]
       user.display_name = auth.info.name
       user.username = auth.info.nickname
       user.email = auth.info.email

       user.remote_avatar_url = auth.info.image if auth.info.image.present?
       auth.provider == "twitter" ?  user.save(:validate => false) :  user.save
      end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



    def after_sign_in_path_for(resource_or_scope)
    	if session[:redirected_from_omniauth] == true

    		session[:redirected_from_omniauth] = nil
            username_user_url(resource_or_scope)

    	else 
    		root_url
    	end
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	def all
		p env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "You are in..!!! Go to edit profile to see the status for the accounts"
			session[:redirected_from_omniauth] = true
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def faq
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :set_user, only: [:account, :password, :profile,:update_info,:update_image]
  def account
  end

  def password
  end

  def notifications
  end

  def profile
  end

  def update_info
   
   @user.update_attributes(user_params)
    if @user.save
    	flash[:notice] = "Your info has been updated."
    	redirect_to root_path(current_user)
        
    end
    	
  end	

  def update_image
   
   @user.update_attributes(user_params)
    if @user.save
    	flash[:notice] = "Your info has been updated."
    	redirect_to root_path(current_user)
        
    end
    	
  end	
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user

      @user = current_user
    end

  def user_params
    params.require(:user).permit(:username, :email, :password,:password_confirmation, :bio, :location,:avatar,:time_zone,:birthday,:reset_password_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:username]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def username
    @redirected_from_ominauth = true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :display_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "WEBSITE" %></title>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">			<script type="text/javascript" src="//use.typekit.net/ncr8orh.js"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if user_signed_in? %>
              <li><%= link_to "Edit profile", settings_profile_url %></li>
              <li><%= link_to "Settings", settings_account_url %></li>
              <li><%= link_to "Logout", logout_url %></li>
            <% else %>
              <li><%= link_to "Login", login_url %></li>
              <li><%= link_to "Join", join_url %></li>
            <% end %>
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "FAQ", faq_url %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Me", current_user%></li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
    <div class="row">
      <div class="columns">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

<script>
  $(document).ready(function() {

      // assuming the controls you want to attach the plugin to
      // have the "datepicker" class set
      $('input.datepicker1').Zebra_DatePicker();
      
  });

   $(document).on('click','#upload_photo',function(){

      $("#photo").trigger('click');
   });
   


  </script>

app/views/pages/faq.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3>What is the meaning to life?</h3>
    <p>42.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="large-8 columns">


    <p>Dolor irure sint Lorem tempor commodo. Aliquip eiusmod non excepteur duis excepteur laborum nostrud laborum amet exercitation amet Lorem. Sint quis dolore consequat velit ullamco ipsum culpa exercitation esse pariatur. Tempor sit adipisicing qui minim irure ea.</p>

    <p>Consectetur nostrud ad elit do incididunt laborum laboris esse cupidatat deserunt et nulla nostrud cillum. Proident cillum id anim Lorem nostrud ex aliqua sit ipsum. Magna ea incididunt occaecat nostrud elit amet culpa reprehenderit labore. Irure consequat fugiat id eiusmod occaecat ex.</p>

    <p>Cillum eiusmod proident ad ex consectetur sit anim ad occaecat magna. Sunt dolor occaecat pariatur ea laborum ex pariatur nostrud exercitation ipsum tempor eiusmod. Ullamco incididunt non sunt proident aliqua exercitation occaecat amet adipisicing elit sunt. Consequat duis ut Lorem est anim officia esse ipsum duis ullamco id. Enim ullamco Lorem do aliquip velit aliqua ullamco ea officia nostrud pariatur eiusmod sit consectetur.</p>



  </div>
  <% unless current_user%>
    <div class="large-4 columns">

      <div class="panel" align="center">
        <a href='users/auth/facebook' class="button facebook"> <i class="fa fa-facebook modal-icons"></i> Sign In with Facebook </a>
    		<a href='users/auth/google_oauth2' class="button google"> <i class="fa fa-google-plus modal-icons"></i> Sign In with Google+ </a>
        <p>Or <%= link_to "login with Email", login_url %>.
      </div>

    </div>
  <% end %>
</div>

app/views/settings/_menu.html.erb
<div class="panel">
  <ul>
    <li><%= link_to "Account", settings_account_url %></li>
    <li><%= link_to "Password", settings_password_url %></li>
    <li><%= link_to "Notifications", settings_notifications_url %></li>
    <li><%= link_to "Profile", settings_profile_url %></li>
  </ul>
</div>

app/views/settings/account.html.erb
<div class="row">
  <div class="medium-4 columns">
    <%= render "menu" %>
  </div>
  <div class="medium-8 columns">
    <h3>Account</h3>
    <% action = params[:action] %>
    
    <%= form_for(@user,:method=>:patch,:url=>settings_update_info_path) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
    <%= hidden_field_tag 'my_action' ,'/settings/account' %>
      <div class="row">
        <div class="small-8">


          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Username</label>
            </div>
            <div class="small-9 columns">
                <%= f.text_field :username , :value => @user.username %>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Email</label>
            </div>
            <div class="small-9 columns">
               <%= f.text_field :email , :value => @user.email%>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Timezone</label>
            </div>
            <div class="small-9 columns">
             <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones%>
            </div>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>

        </div>
      </div>
    <%end%>
  

  </div>
</div>

app/views/settings/notifications.html.erb
<div class="row">
  <div class="medium-4 columns">
    <%= render "menu" %>
  </div>
  <div class="medium-8 columns">
    Notifications settings
  </div>
</div>

app/views/settings/password.html.erb
<div class="row">
  <div class="medium-4 columns">
    <%= render "menu" %>
  </div>
  <div class="medium-8 columns">
  	<h3>Password</h3>
    <%= form_for(@user,:method=>:patch,:url=>settings_update_info_path) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
     <div class="row">
        <div class="small-8">

  <%#= f.hidden_field :reset_password_token %>
  <%= hidden_field_tag 'my_action' ,'/settings/password' %>
  <div><%= f.label :password, "New password" %><br />
    <%= f.password_field :password, autofocus: true, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation, "Confirm new password" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.submit "Change my password" %></div>
</div>
</div>
<% end %>
  </div>
</div>

app/views/settings/profile.html.erb
<div class="row">
  <div class="medium-4 columns">
    <%= render "menu" %>
  </div>
  <div class="medium-8 columns">
    <h3>Profile</h3>
    <%= form_for(@user,:html => { :multipart => true },:method=>:post,:url=>settings_update_image_path) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="small-8">

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Avatar</label>
            </div>
            <div class="small-9 columns">
              <%if @user.avatar_file_name!='default.jpeg'%>
                <%= link_to image_tag(@user.avatar),"javascript:void(0)",:id=>'upload_photo' %>
              <% elsif @user.remote_avatar_url.present?%>
                 <%=link_to image_tag(@user.remote_avatar_url),"javascript:void(0)",:id=>'upload_photo' %>
            
           <%else %>
             <%= link_to image_tag('default.jpeg'),"javascript:void(0)",:id=>'upload_photo' %>
          <%end%>
             <br/>
             <div class="hide"><%= f.file_field :avatar,:id=>"photo" %><div>
            <%#= f.hidden_field :avatar, :id => "hidden_filename" %>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Full name</label>
            </div>
            <div class="small-9 columns">
              <%= f.text_field :username , :value => @user.username %>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Location</label>
            </div>
            <div class="small-9 columns">
              <%= f.text_field :location , :value => @user.location ? @user.location : ""%>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Bio</label>
            </div>
            <div class="small-9 columns">
             <%= f.text_area :bio , :value => @user.bio ? @user.bio : ""%>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <label for="right-label" class="right inline">Birthday</label>
            </div>
            <div class="small-9 columns">
              <%= f.text_field :birthday , :value => @user.birthday ? @user.birthday : "",:class=>'datepicker1'%>
            </div>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>

        </div>
      </div>
    <%end%>

    
  </div>
</div>
<style>
  .hide{
    display:none;
  }
</style>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username , :value => (@redirected_from_ominauth ? @user.display_name.downcase.gsub(" ","") : "")   %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <% if @user.remote_avatar_url.present? %>
  <div class="field">
   <%= f.label :Avatar %><br>
   <%= image_tag @user.remote_avatar_url %>
   </div>
   <%else %>
    <div class="field">
   <%= f.label "Default Avatar" %><br>
   <%= image_tag 'default.jpeg'%>
   </div>

  <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Display name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.display_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="columns">
    <p>Email: <%= @user.email %></p>
    <p>Display name:<%= @user.display_name %></p>
    <p>Username: <%= @user.username %></p>
    <p>User id: <%= @user.id %></p>
    <p><% if @user.remote_avatar_url.present? %>
     Avatar
   <%= image_tag @user.remote_avatar_url %>
   
   <%else %>
    Default Avatar:
   <%= image_tag 'default.jpeg'%>
   

  <%end%></p>
  </div>
</div>

app/views/users/username.html.erb
<%= render 'form' %>